# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Daemonite
tagline:             'Home of the motley daemon crew.'
description:         'Home of the motley daemon crew.'
url:                 http://blog.daemon.com.au
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              'Daemonites'
  url:               https://twitter.com/daemonites
  email:             modius@daemon.com.au

# Custom vars
version:             1.0.0
github:
  repo:           https://github.com/daemonite
